// frontend/src/app/shared/_ui/icon/icon-names-data.ts

export const ICONS = [
    'drop-down',
    'paper',
    'task',
    'palette',
    'plus-in-two-square',
    'minus-in-circle',
    'cross-in-circle',
    'check-in-circle',
    'check-in-circle-green',
    'iterations',
    'iteration-in-circle',
    'clear',
    'arrow-down',
    'bug-stroked',
    'error',
    'clock',
    'search',
    'edit',
    'basket',
    'select',
    'tablet',
    'office',
    'warning',
    'chat',
    'tasks',
    'alarms',
    'plus',
    'minus',
    'kanban',
    'reports',
    'team',
    'projects',
    'projects-bold',
    'tack',
    'star',
    'info',
    'ellipsis',
    'paper-with-pen',
    'copy',
    'download',
    'zip-file',
    'download2',
    'zoom-minus',
    'zoom-plus',
    'rotate',
    'check-in-circle-stroked',
    'circle-behind-circle',
    'table',
    // 'development',
    'ios',
    'web',
    'backend',
    'cards-large',
    'cards-medium',
    'cards-small',
    'sp2', // временно
    'soft-artel', // временно
    'sort',
    'dislike',
    'pause',
    'umbrella',
    'pharmacy',
    'camera-in-circle',
    'android',
    'website',
    'star-stroked',
    'folder',
    'monitor',
    'file-pdf',
    'camera',
    'suitcase',
    'rub-in-circle',
    'hourglass-in-circle',
    'arrow-in-circle',
    'pharmacy-in-circle',
    'paperclip',
    'send',
    'pinned-list',
    'bell',
    'bell-crossed-out',
    'bell-crossed-out-fill',
    'reply',
    'reply-bold',
    'pushpin',
    'two-people',
    'three-people',
    'people-in-circle',
    'forbidden-sign',
    'hammer',
    'hammer-stroked',
    'question-mark-in-circle',
    'done',
    'task-type-qa',
    'task-type-education',
    'task-type-design',
    'task-type-analytic',
    'task-type-research',
    'task-type-support',
    'task-type-planning',
    'task-type-documentation',
    'task-type-task',
    'settings',
    'paper-plane',
    'mail',
    'phone',
    'check',
    'play',
    'apple',
    'mobile',
    'picture-in-circle',
    'plus-and-lines',
    'chain',
    'messages',
    'videocamera',
    'meeting',
    'paper-list',
    'expand',
    'mark-in-star',
    'plus-in-square',
    'image-button',
    'upload-button',
    'priority-urgent',
    'priority-important',
    'priority-inorder',
    'human',
    'question-filled',
    'human-in-circle',
    'history',

    'task-status-draft',
    'task-status-approval',
    'task-status-work',
    'task-status-review',
    'task-status-deploy',
    'task-status-test',
    'task-status-close',

    'notifications',
    'add-project',

    'play-in-filled-circle',
    'pause-in-filled-circle',
    'arrow-in-filled-circle',
    'crooked-arrow-in-filled-circle',
    'crooked-arrow-in-filled-circle-back',
    'arrow-in-square',
    'papers',
    'arrows-in-square',

    'tablet-device',
    'shell-device',

    'bug-type-fn',
    'bug-type-ui',
    'bug-type-ux',
    'bug-type-spec',

    'bug-block',
    'bug-critical',
    'bug-major',
    'bug-minor',
    'bug-trivial',

    'box',
    'create-product',

    'devices',
    'branch',

    'bug-severity',
    'left-arrow-in-filled-circle',
    'task-in-circle',
    'bell-filled',

    'upload-file',

    'award',

    'home',
    'logout',
    'archive_in',
    'archive_out',

    'rocket',
    'at',

    'eye',
    'eye-crossed',

    'hourglass',

    // Для страницы интеграции
    'git',
    'github',
    'gitlab',
    'code-commit',
    'gerrit',
    'microsoft',
    'sync-on',
    'sync-off',
    'check-off-square',
    'check-on-square',
    'check-on-disabled-square',
    'clipboard',
    'info-filled',

    'inactive-user',

    // Для check-box в виде тумблера
    'switch-on',
    'switch-off',

    'sync',
    'human-in-circle-stroked',
    'payments',
    'support',
    'umbrella-stroked',
    'flag-ru',

    // Spinners & loaders
    'small-loading',
    'spinner',

    // departments
    'management',
    'marketing',
    'support',

    'project',
    'browser',
    'hash',

    'tv',
    'watch',
    'smart-home',
    'pad',
    'console',
    'task-type-frontend',
    'task-type-backend',
    'task-type-devops',
    'task-type-tests',
    
    'pharmacy-stroked',
    'arrow-top',
    'arrow-right',
    'arrow-left',
    'spanner',
    'calculator',
    'moduls',
    'security-account-outline',
    'payments',
    
    'journal',
    'moonline',
    'bonus',
    'deduction',
    'bi-book',
    'collapse',
    'back',
    'upload',
    'link',
    'icon-checked-square',
    'icon-copy',
    'comment',
    'question-circle',
    'security',
    'lock',
    'unlock',
    'ai',
] as const

export type IconName = typeof ICONS[ number ]